//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 10:52:24 PM MEZ 
//


package com.github.kayak.canio.kcd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}Label" minOccurs="0"/>
 *         &lt;element ref="{}LabelGroup" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="slope" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *       &lt;attribute name="intercept" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "labelOrLabelGroup"
})
@XmlRootElement(name = "Value")
public class Value {

    @XmlElements({
        @XmlElement(name = "Label", type = Label.class),
        @XmlElement(name = "LabelGroup", type = LabelGroup.class)
    })
    protected List<BasicLabelType> labelOrLabelGroup;
    @XmlAttribute
    protected Double slope;
    @XmlAttribute
    protected Double intercept;

    /**
     * Gets the value of the labelOrLabelGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelOrLabelGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelOrLabelGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * {@link LabelGroup }
     * 
     * 
     */
    public List<BasicLabelType> getLabelOrLabelGroup() {
        if (labelOrLabelGroup == null) {
            labelOrLabelGroup = new ArrayList<BasicLabelType>();
        }
        return this.labelOrLabelGroup;
    }

    /**
     * Gets the value of the slope property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getSlope() {
        if (slope == null) {
            return  1.0D;
        } else {
            return slope;
        }
    }

    /**
     * Sets the value of the slope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSlope(Double value) {
        this.slope = value;
    }

    /**
     * Gets the value of the intercept property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getIntercept() {
        if (intercept == null) {
            return  0.0D;
        } else {
            return intercept;
        }
    }

    /**
     * Sets the value of the intercept property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIntercept(Double value) {
        this.intercept = value;
    }

}
