//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.24 at 08:37:14 PM CEST 
//


package com.github.kayak.canio.kcd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://kayak.2codeornot2code.org/1.0}BasicSignalType">
 *       &lt;sequence>
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}MuxGroup" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}Notes" minOccurs="0"/>
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}Consumer" minOccurs="0"/>
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}Value" minOccurs="0"/>
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}LabelSet" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "muxGroup",
    "notes",
    "consumer",
    "value",
    "labelSet"
})
@XmlRootElement(name = "Multiplex")
public class Multiplex
    extends BasicSignalType
{

    @XmlElement(name = "MuxGroup", required = true)
    protected List<MuxGroup> muxGroup;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "Consumer")
    protected Consumer consumer;
    @XmlElement(name = "Value")
    protected Value value;
    @XmlElement(name = "LabelSet")
    protected LabelSet labelSet;

    /**
     * Gets the value of the muxGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the muxGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMuxGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MuxGroup }
     * 
     * 
     */
    public List<MuxGroup> getMuxGroup() {
        if (muxGroup == null) {
            muxGroup = new ArrayList<MuxGroup>();
        }
        return this.muxGroup;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the consumer property.
     * 
     * @return
     *     possible object is
     *     {@link Consumer }
     *     
     */
    public Consumer getConsumer() {
        return consumer;
    }

    /**
     * Sets the value of the consumer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Consumer }
     *     
     */
    public void setConsumer(Consumer value) {
        this.consumer = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setValue(Value value) {
        this.value = value;
    }

    /**
     * Gets the value of the labelSet property.
     * 
     * @return
     *     possible object is
     *     {@link LabelSet }
     *     
     */
    public LabelSet getLabelSet() {
        return labelSet;
    }

    /**
     * Sets the value of the labelSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelSet }
     *     
     */
    public void setLabelSet(LabelSet value) {
        this.labelSet = value;
    }

}
